# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Disable laptop display automatically when an external monitor is connected
exec-once = uwsm-app -- ~/.config/hypr/scripts/monitor-external-watch
